### ISSUE TITLE
Wishlist: Allow to set repos from outside?

### ISSUE THREAD

**Issue by jbglaw** [mikpe/buildcross#2]
Hi!

As mentioned, I'd be interested in calling `buildcross` as one part of my http://toolchain.lug-owl.de/ efforts. Right now, it's using released components. It would be nice for me if I could force it to use master versions for all repos. Maybe that could be done by a config file (sourced, containing alternative assignments for `$BINUTILS_VSN`, `$GCC_VSN` etc.  Most of the needed infrastructure to fetch a GIT repo and set it to a given branch/tag is already there, so I guess it would be pretty straight forward to source such an assignments file at around line 700.

Any thoughts/comments/notes about this?

Thanks,
  Jan-Benedict

**Comment by jbglaw** [comment]
I'd even think about a separate `--all-master` option to use the latest HEAD from all components (and _not_ a known-working old version) to actually _see_ what's _currently_ broken.

**Comment by mikpe** [comment]
> Hi!
> 
> As mentioned, I'd be interested in calling `buildcross` as one part of my http://toolchain.lug-owl.de/ efforts. Right now, it's using released components. It would be nice for me if I could force it to use master versions for all repos. Maybe that could be done by a config file (sourced, containing alternative assignments for `$BINUTILS_VSN`, `$GCC_VSN` etc. Most of the needed infrastructure to fetch a GIT repo and set it to a given branch/tag is already there, so I guess it would be pretty straight forward to source such an assignments file at around line 700.
> 
> Any thoughts/comments/notes about this?
> 
> Thanks, Jan-Benedict

This should be doable, just needs adjusting the command-line arguments parsing.

**Comment by mikpe** [comment]
> I'd even think about a separate `--all-master` option to use the latest HEAD from all components (and _not_ a known-working old version) to actually _see_ what's _currently_ broken.

I think this needs to be separate from the other item. Also, for this to be effective, we'd need to reroute targets using tarballs to get everything from git, and in that case do that by default, in effect dropping the use of tarballs.

**Comment by jbglaw** [comment]
For plain upstream GCC, there'll probably be proper tags for the requested versions. Generally change over to GIT repos?

**Comment by mikpe** [comment]
> Generally change over to GIT repos?

That's the plan, yes.

**Comment by mikpe** [comment]
I've just released v7.0.0. It switches most builds over to GIT (which took a lot of tweaking), and also lets the user override where the auxiliary directories are located. I have not addressed the "build from HEAD" part.

**Comment by jbglaw** [comment]
Good work! I'm just looking through the patches and will do adjustments as needed on my CI builder.
Seems that was quite some work, looking at all the little tweaks you had to apply for all the targets.

**Comment by jbglaw** [comment]
Seems to work for me, I'll close this ticket. Thanks a lot!
